name: "ArgoCD Application Sync Action"
description: "Sync your ArgoCD application from GitHub"
author: "omegion"
inputs:
  address:
    description: "ArgoCD server address"
    required: true
  token:
    description: "ArgoCD token"
    required: true
  appName:
    description: "Application name to sync"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"