name: Integration Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          githubToken: ${{ secrets.GT_VAULT_AUTH_TOKEN }}
          secrets: |
            argocd/data/token admin | ARGOCD_TOKEN ;

      - name: Self test
        id: selftest
        uses: ./
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          token: ${{ steps.secrets.outputs.ARGOCD_TOKEN }}
          action: sync
          appName: argocd-apps
          image: latest

